import './style.css';
import * as XLSX from 'xlsx';
import { Camera, CameraResultType, CameraSource } from '@capacitor/camera';
import { Share } from '@capacitor/share';
import { jsPDF } from 'jspdf';

const KEY='stok-real-final-v1';
const initial={items:[],imports:[],checks:[],settings:{storeName:'STOK REAL'}};
let db=load(); let view='dashboard'; let search='';
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(initial)}catch{return structuredClone(initial)}}
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const fmt=n=>Number(n||0).toLocaleString('id-ID',{maximumFractionDigits:2});
const dt=iso=>new Date(iso||Date.now()).toLocaleString('id-ID');
function latestCheck(code){return db.checks.filter(x=>x.itemCode===code).sort((a,b)=>b.checkedAt.localeCompare(a.checkedAt))[0]}
function checkedToday(code){const d=new Date().toISOString().slice(0,10);return db.checks.some(x=>x.itemCode===code&&x.checkedAt.slice(0,10)===d)}
function render(){document.querySelector('#app').innerHTML=`<header class="top"><h1>STOK REAL</h1><small>Pemeriksaan stok bertahap • iReap harian</small></header><main class="wrap"><div id="content"></div></main><nav class="bottom"><button data-v="dashboard">🏠<span>Dashboard</span></button><button data-v="history">📋<span>Riwayat</span></button><button data-v="report">📊<span>Laporan</span></button><button data-v="backup">💾<span>Backup</span></button></nav>`;document.querySelectorAll('.bottom button').forEach(b=>b.onclick=()=>{view=b.dataset.v;renderView()});renderView()}
function renderView(){const c=document.querySelector('#content');if(view==='dashboard')dashboard(c);if(view==='history')history(c);if(view==='report')report(c);if(view==='backup')backup(c)}
function dashboard(c){const checked=new Set(db.checks.filter(x=>x.checkedAt.slice(0,10)===new Date().toISOString().slice(0,10)).map(x=>x.itemCode));const real=db.checks.reduce((s,x)=>s+Number(x.real||0),0);const diff=db.checks.reduce((s,x)=>s+Number(x.diff||0),0);c.innerHTML=`<section class="cards"><div class="card"><b>${db.items.length}</b><span>Barang</span></div><div class="card"><b>${fmt(db.items.reduce((s,x)=>s+Number(x.quantity||0),0))}</b><span>Stok iReap terbaru</span></div><div class="card"><b>${fmt(real)}</b><span>Total real dari cek</span></div><div class="card"><b>${checked.size}</b><span>Cek hari ini</span></div><div class="card"><b>${Math.max(0,db.items.length-checked.size)}</b><span>Belum dicek hari ini</span></div><div class="card"><b>${diff>0?'+':''}${fmt(diff)}</b><span>Total selisih riwayat</span></div></section><div class="search">🔍 <input id="search" value="${esc(search)}" placeholder="Cari kode, nama, barcode, kategori..."></div><div class="actions"><button class="primary" id="add">＋ INPUT BARANG</button><button class="secondary" id="imp">📥 IMPORT iREAP</button><input id="file" type="file" accept=".xlsx,.xls,.csv" hidden></div><section class="panel"><div class="toolbar"><button class="ghost" id="all">Semua</button><button class="ghost" id="not">Belum dicek hari ini</button></div><div class="panel-title">Barang</div><div id="list"></div></section>`;document.getElementById('search').oninput=e=>{search=e.target.value;drawList()};document.getElementById('add').onclick=()=>itemModal();document.getElementById('imp').onclick=()=>document.getElementById('file').click();document.getElementById('file').onchange=importIreap;document.getElementById('all').onclick=()=>drawList(false);document.getElementById('not').onclick=()=>drawList(true);drawList()}
function drawList(onlyUnchecked=false){const n=search.toLowerCase().trim();let arr=db.items.filter(x=>[x.code,x.name,x.barcode,x.category].join(' ').toLowerCase().includes(n));if(onlyUnchecked)arr=arr.filter(x=>!checkedToday(x.code));const el=document.getElementById('list');el.innerHTML=arr.slice(0,200).map(x=>{const lc=latestCheck(x.code);return `<article class="item"><div><strong>${esc(x.name||'-')}</strong><div class="muted">${esc(x.code)} • ${esc(x.category||'-')} • ${esc(x.uom||'')}</div><div class="muted">iReap terbaru: ${fmt(x.quantity)}${checkedToday(x.code)?' • ✓ dicek hari ini':''}${lc?' • cek terakhir: '+dt(lc.checkedAt):''}</div></div><div class="qty">${fmt(x.quantity)}</div><button class="check" data-code="${esc(x.code)}">CEK</button></article>`}).join('')||'<div class="empty">Belum ada barang. Import iReap atau input manual.</div>';el.querySelectorAll('.check').forEach(b=>b.onclick=()=>checkModal(b.dataset.code))}
function itemModal(item=null){openModal(`<h2>${item?'Edit':'Input'} Barang</h2><form class="form" id="itemForm"><div class="field"><label>Kode Barang / Item Code</label><input name="code" value="${esc(item?.code||'')}" ${item?'readonly':''} required></div><div class="field"><label>Nama Barang</label><input name="name" value="${esc(item?.name||'')}" required></div><div class="row"><div class="field"><label>Kategori</label><input name="category" value="${esc(item?.category||'')}"></div><div class="field"><label>Satuan</label><input name="uom" value="${esc(item?.uom||'pcs')}"></div></div><div class="row"><div class="field"><label>Stok Sistem</label><input name="quantity" type="number" step="any" value="${item?.quantity??0}"></div><div class="field"><label>Barcode</label><input name="barcode" value="${esc(item?.barcode||item?.code||'')}"></div></div><div class="sheet-actions"><button type="button" class="ghost" id="cancel">Batal</button><button class="primary">Simpan</button></div></form>`);document.getElementById('cancel').onclick=closeModal;document.getElementById('itemForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);const x={code:f.get('code').trim(),name:f.get('name').trim(),category:f.get('category').trim(),uom:f.get('uom').trim(),quantity:Number(f.get('quantity')||0),barcode:f.get('barcode').trim()};if(!x.code||!x.name)return alert('Kode dan nama wajib diisi.');const i=db.items.findIndex(z=>z.code===x.code);if(i>=0)db.items[i]={...db.items[i],...x};else db.items.push({...x,minStock:0,cost:0,value:0});save();closeModal();renderView()}}
async function importIreap(e){const f=e.target.files[0];if(!f)return;try{const wb=XLSX.read(await f.arrayBuffer(),{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(ws,{defval:''});let added=0,updated=0;const importedAt=new Date().toISOString();for(const r of rows){const code=String(r['Item Code']??r['Kode Barang']??r['Code']??'').trim();if(!code)continue;const x={code,name:String(r['Item Name']??r['Nama Barang']??''),category:String(r['Category']??r['Kategori']??''),quantity:Number(r['Quantity']??r['Qty']??0)||0,minStock:Number(r['Min Stock']??0)||0,uom:String(r['UoM']??r['Satuan']??''),cost:Number(r['Cost @ IDR']??r['Cost']??0)||0,value:Number(r['Value IDR']??r['Value']??0)||0,barcode:String(r['Barcode']??code)};const i=db.items.findIndex(z=>z.code===code);if(i>=0){db.items[i]={...db.items[i],...x};updated++}else{db.items.push(x);added++} }db.imports.push({id:crypto.randomUUID(),importedAt,source:f.name,count:rows.length,items:db.items.length});save();renderView();alert(`Import selesai.\nBaris: ${rows.length}\nBaru: ${added}\nDiperbarui: ${updated}`)}catch(err){alert('Gagal import: '+err.message)}e.target.value=''}
async function checkModal(code){const x=db.items.find(z=>z.code===code);if(!x)return;const old=latestCheck(code);openModal(`<h2>Cek Real</h2><div class="detail"><b>${esc(x.name)}</b><div class="muted">${esc(x.code)} • ${esc(x.category||'-')}</div><p>Stok iReap saat ini: <strong>${fmt(x.quantity)} ${esc(x.uom||'')}</strong></p></div><form class="form" id="checkForm"><div class="field"><label>Stok Fisik / Real</label><input id="real" name="real" type="number" step="any" required autofocus></div><div class="field"><label>Catatan</label><textarea name="note" rows="2"></textarea></div><div class="field"><label>Foto Bukti</label><div class="toolbar"><button type="button" class="secondary" id="camera">📷 Kamera</button><button type="button" class="ghost" id="gallery">🖼️ Galeri</button></div><div class="photos" id="photos"></div></div><div class="sheet-actions"><button type="button" class="ghost" id="cancel">Batal</button><button class="primary">Simpan Cek</button></div></form>`);let photos=[];const photoEl=document.getElementById('photos');const addPhoto=p=>{if(p){photos.push(p);photoEl.insertAdjacentHTML('beforeend',`<img src="${p}">`)}};document.getElementById('camera').onclick=async()=>{try{const p=await Camera.getPhoto({quality:70,resultType:CameraResultType.DataUrl,source:CameraSource.Camera});addPhoto(p.dataUrl)}catch{}};document.getElementById('gallery').onclick=async()=>{try{const p=await Camera.getPhoto({quality:70,resultType:CameraResultType.DataUrl,source:CameraSource.Photos});addPhoto(p.dataUrl)}catch{}};document.getElementById('cancel').onclick=closeModal;document.getElementById('checkForm').onsubmit=e=>{e.preventDefault();const real=Number(document.getElementById('real').value);if(!Number.isFinite(real))return;const system=Number(x.quantity||0);db.checks.push({id:crypto.randomUUID(),itemCode:x.code,itemName:x.name,system,real,diff:real-system,note:new FormData(e.target).get('note')||'',photos,checkedAt:new Date().toISOString(),checkerName:'',checkerSignature:'',guardianName:'',guardianSignature:'',approved:false,locked:false,correctionOf:null});save();closeModal();renderView();approvalModal(db.checks.at(-1).id)}}
function approvalModal(id){const ch=db.checks.find(x=>x.id===id);if(!ch)return;openModal(`<h2>Persetujuan Hasil Cek</h2><div class="detail"><b>${esc(ch.itemName)}</b><p>Sistem: <strong>${fmt(ch.system)}</strong> • Real: <strong>${fmt(ch.real)}</strong> • Selisih: <strong>${ch.diff>0?'+':''}${fmt(ch.diff)}</strong></p><div class="muted">${dt(ch.checkedAt)}</div></div><form class="form" id="approval"><div class="field"><label>Nama Pemeriksa</label><input name="checkerName" required></div><canvas class="sig" id="sig1"></canvas><div class="field"><label>Nama Penjaga Toko</label><input name="guardianName" required></div><canvas class="sig" id="sig2"></canvas><div class="sheet-actions"><button type="button" class="ghost" id="close">Nanti</button><button class="primary">Setujui & Kunci</button></div></form>`);const s1=signature(document.getElementById('sig1')),s2=signature(document.getElementById('sig2'));document.getElementById('close').onclick=closeModal;document.getElementById('approval').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);ch.checkerName=f.get('checkerName');ch.guardianName=f.get('guardianName');ch.checkerSignature=s1();ch.guardianSignature=s2();ch.approved=true;ch.locked=true;ch.approvedAt=new Date().toISOString();save();closeModal();renderView()}}
function signature(canvas){const ctx=canvas.getContext('2d');ctx.lineWidth=2;ctx.lineCap='round';let down=false,last=null;const pos=e=>{const r=canvas.getBoundingClientRect();const t=e.touches?.[0];return{x:(t?t.clientX:e.clientX)-r.left,y:(t?t.clientY:e.clientY)-r.top}};const start=e=>{down=true;last=pos(e);e.preventDefault()};const move=e=>{if(!down)return;const p=pos(e);ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p;e.preventDefault()};const end=()=>down=false;['pointerdown','touchstart'].forEach(x=>canvas.addEventListener(x,start,{passive:false}));['pointermove','touchmove'].forEach(x=>canvas.addEventListener(x,move,{passive:false}));['pointerup','pointerleave','touchend'].forEach(x=>canvas.addEventListener(x,end));return()=>canvas.toDataURL('image/png')}
function history(c){const arr=db.checks.slice().sort((a,b)=>b.checkedAt.localeCompare(a.checkedAt));c.innerHTML=`<section class="panel"><div class="panel-title">Riwayat Pengecekan</div><div class="toolbar"><input id="hf" class="field" placeholder="Cari barang/kode"></div><div id="hist"></div></section>`;const draw=()=>{const q=document.getElementById('hf').value.toLowerCase();document.getElementById('hist').innerHTML=arr.filter(x=>(x.itemCode+' '+x.itemName).toLowerCase().includes(q)).map(x=>`<article class="item"><div><strong>${esc(x.itemName)}</strong><div class="muted">${dt(x.checkedAt)} • Sistem ${fmt(x.system)} • Real ${fmt(x.real)} • Selisih ${x.diff>0?'+':''}${fmt(x.diff)}</div><div class="muted">${x.approved?'🔒 Disetujui & dikunci':'🟡 Menunggu persetujuan'}</div></div><button class="check" data-id="${x.id}">LIHAT</button></article>`).join('')||'<div class="empty">Belum ada riwayat.</div>';document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>detailCheck(b.dataset.id))};document.getElementById('hf').oninput=draw;draw()}
function detailCheck(id){const x=db.checks.find(z=>z.id===id);openModal(`<h2>Detail Pemeriksaan</h2><div class="detail"><b>${esc(x.itemName)}</b><div>${esc(x.itemCode)}</div><p>Sistem ${fmt(x.system)} → Real ${fmt(x.real)} → Selisih ${x.diff>0?'+':''}${fmt(x.diff)}</p><div class="muted">${dt(x.checkedAt)}</div><p>${esc(x.note||'')}</p>${x.approved?`<span class="status">🔒 DIKUNCI</span>`:'<span class="status warn">MENUNGGU PERSETUJUAN</span>'}</div><div class="photos">${(x.photos||[]).map(p=>`<img src="${p}">`).join('')}</div><p>Pemeriksa: ${esc(x.checkerName||'-')}<br>Penjaga: ${esc(x.guardianName||'-')}</p>${!x.locked?`<button class="primary" id="approve">Tanda tangan & kunci</button>`:`<button class="secondary" id="corr">Buat Koreksi</button>`}`);if(!x.locked)document.getElementById('approve').onclick=()=>approvalModal(x.id);else document.getElementById('corr').onclick=()=>correction(x.id)}
function correction(id){const old=db.checks.find(x=>x.id===id);const real=Number(prompt(`Koreksi ${old.itemName}. Stok sistem snapshot tetap ${old.system}.\nMasukkan stok real yang benar:`));if(!Number.isFinite(real))return;db.checks.push({...old,id:crypto.randomUUID(),real,diff:real-old.system,checkedAt:new Date().toISOString(),approved:false,locked:false,correctionOf:id,note:(old.note||'')+' | Koreksi dari '+id,checkerSignature:'',guardianSignature:'',checkerName:'',guardianName:''});save();renderView()}
function report(c){c.innerHTML=`<section class="panel"><div class="panel-title">Laporan & Ekspor</div><div class="toolbar"><input id="from" type="date"><input id="to" type="date"></div><div class="toolbar"><button class="primary" id="pdf">PDF</button><button class="secondary" id="xlsx">XLSX</button><button class="ghost" id="csv">CSV</button><button class="ghost" id="share">Bagikan</button></div><div id="rt"></div></section>`;const renderTable=()=>{const a=document.getElementById('from').value,b=document.getElementById('to').value;const rows=db.checks.filter(x=>(!a||x.checkedAt.slice(0,10)>=a)&&(!b||x.checkedAt.slice(0,10)<=b));document.getElementById('rt').innerHTML=`<table class="report-table"><thead><tr><th>Tanggal</th><th>Kode</th><th>Barang</th><th>Sistem</th><th>Real</th><th>Selisih</th><th>Status</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(dt(x.checkedAt))}</td><td>${esc(x.itemCode)}</td><td>${esc(x.itemName)}</td><td>${fmt(x.system)}</td><td>${fmt(x.real)}</td><td>${x.diff>0?'+':''}${fmt(x.diff)}</td><td>${x.locked?'Terkunci':'Draft'}</td></tr>`).join('')}</tbody></table>`};document.getElementById('from').onchange=renderTable;document.getElementById('to').onchange=renderTable;renderTable();document.getElementById('pdf').onclick=()=>exportPdf();document.getElementById('xlsx').onclick=()=>exportXlsx();document.getElementById('csv').onclick=()=>exportCsv();document.getElementById('share').onclick=()=>shareReport()}
function selectedRows(){return db.checks.slice().sort((a,b)=>b.checkedAt.localeCompare(a.checkedAt))}
function exportCsv(){const a=selectedRows(),s='Tanggal,Kode,Nama,Sistem,Real,Selisih,Status\n'+a.map(x=>[dt(x.checkedAt),x.itemCode,x.itemName,x.system,x.real,x.diff,x.locked?'Terkunci':'Draft'].map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n');download('stok-real.csv',s,'text/csv')}
function exportXlsx(){const a=selectedRows().map(x=>({Tanggal:dt(x.checkedAt),Kode:x.itemCode,Nama:x.itemName,Sistem:x.system,Real:x.real,Selisih:x.diff,Status:x.locked?'Terkunci':'Draft'}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(a),'Pengecekan');XLSX.writeFile(wb,'stok-real.xlsx')}
function exportPdf(){const d=new jsPDF();d.setFontSize(16);d.text(db.settings.storeName||'STOK REAL',14,16);d.setFontSize(10);d.text('Laporan Pengecekan Stok',14,24);let y=34;selectedRows().slice(0,35).forEach(x=>{const line=`${dt(x.checkedAt)} | ${x.itemCode} | ${x.itemName} | ${x.system} -> ${x.real} | ${x.diff}`;d.text(line.slice(0,110),14,y);y+=6;if(y>280){d.addPage();y=16}});d.save('stok-real.pdf')}
async function shareReport(){try{const text=selectedRows().map(x=>`${dt(x.checkedAt)} | ${x.itemCode} | ${x.itemName} | Sistem ${x.system} | Real ${x.real} | Selisih ${x.diff}`).join('\n');await Share.share({title:'STOK REAL',text})}catch{alert('Bagikan tidak tersedia. Gunakan tombol ekspor lalu pilih WhatsApp/Drive dari menu berbagi Android.')}}
function backup(c){c.innerHTML=`<section class="panel"><div class="panel-title">Backup / Restore</div><div class="detail"><b>${db.items.length}</b> barang • <b>${db.checks.length}</b> pengecekan • <b>${db.imports.length}</b> import</div><div class="sheet-actions"><button class="primary" id="b">💾 Buat Backup</button><button class="secondary" id="r">♻️ Restore</button><input id="rf" type="file" accept=".json" hidden></div><p class="muted">Backup mencakup master barang, histori import, pemeriksaan, foto, tanda tangan, dan pengaturan. Restore mengganti data saat ini.</p></section>`;document.getElementById('b').onclick=()=>download('STOKREAL_BACKUP_'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify(db),'application/json');document.getElementById('r').onclick=()=>document.getElementById('rf').click();document.getElementById('rf').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!Array.isArray(d.items)||!Array.isArray(d.checks))throw Error('Format backup tidak valid');if(confirm(`Restore ${d.items.length} barang dan ${d.checks.length} pengecekan? Data saat ini akan diganti.`)){db=d;save();render()}}catch(err){alert('Restore gagal: '+err.message)}};r.readAsText(f)}}
function openModal(html){closeModal();const d=document.createElement('div');d.className='modal';d.innerHTML=`<div class="sheet">${html}</div>`;document.body.appendChild(d)}function closeModal(){document.querySelector('.modal')?.remove()}function download(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
render();
